In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
data = {"Department": ["HR", "IT", "Finance", "IT"]}
df = pd.DataFrame(data)
df

  Department
0         HR
1         IT
2    Finance
3         IT

In [7]:
le = LabelEncoder()
df["Encoded"] = le.fit_transform(df["Department"])
df

  Department  Encoded
0         HR        1
1         IT        2
2    Finance        0
3         IT        2

In [8]:
pd.get_dummies(df["Department"])

   Finance     HR     IT
0    False   True  False
1    False  False   True
2     True  False  False
3    False  False   True